baseURL = "https://iowafloyd.github.io/"
languageCode = "en-gb"
title = "iowafloyd - an engineering blog"
theme = "hugo-blog-awesome"

[[params.socialIcons]]
 name = "github"
 url = "https://github.com/hugo-sid"

[[params.socialIcons]]
 name = "Rss"
 url = "/index.xml"

[[params.socialIcons]]
 name = "LinkedIn"
 url = "https://www.linkedin.com/in/cameronneff/"

[params]
 goToTop = true

[caches]
 [caches.images]
  dir = ":cacheDir/images"

# Enable emojis globally
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

[markup]
 [markup.highlight]
  noClasses = false
 [markup.goldmark.renderer]
  unsafe = true
 [markup.tableOfContents]
  startLevel = 2
  endLevel = 4
  ordered = false

[Languages.en-gb]
 languageName = "English"
 languageCode = "en-gb"
 contentDir = "content/en"
 weight = 1

[Languages.en-gb.menu]
 [[Languages.en-gb.menu.main]]
  pageRef = "/"
  name = "Home"
  url = "/"
  weight = 10
 [[Languages.en-gb.menu.main]]
  pageRef = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 20
 [[Languages.en-gb.menu.main]]
  pageRef = "about"
  name = "About"
  url = "/about/"
  weight = 30

[Languages.en-gb.params]
 defaultColor = "dark"
 mainSections = ["posts"]
 toc = true
 tocOpen = true
 goToTop = true
# additionalScripts = ["js/custom.js", "js/custom-2.js"]
 dateFormat = "YYYY/mm/dd"
 rssFeedDescription = "summary"

[Languages.en-gb.params.author]
 intro = ""
 name = "Cameron"
 description = "An engineer's blog"

[Languages.en-gb.params.webmanifest]
 name = "sitename"
 short_name = "sitename"
 start_url = "/"
 theme_color = "#434648"
 background_color = "#fff"
 display = "standalone"